# Generated by Django 4.0.7 on 2022-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(choices=[('ADETIKOPE', 'ADETIKOPE'), ('LEGBASSITO', 'LEGBASSITO'), ('BAGUIDA', 'BAGUIDA'), ('BE_EST', 'BE_EST'), ('BE_CENTRE', 'BE_CENTRE'), ('BE_OUEST', 'BE_OUEST'), ('AFLAO_SAGBADO', 'AFLAO_SAGBADO'), ('AFLAO_GAKLI', 'AFLAO_GAKLI'), ('VAKPOSSITO', 'VAKPOSSITO'), ('AGOENYIVE', 'AGOENYIVE'), ('ZANGUERA', 'ZANGUERA'), ('TOGBLE', 'TOGBLE'), ('AMOUTIVE', 'AMOUTIVE')], max_length=200)),
            ],
        ),
    ]
