# Generated by Django 4.0.7 on 2022-10-12 11:06

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('localisation', models.URLField(max_length=150)),
                ('commune', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Pharms_de_garde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_garde', models.BooleanField(default=True)),
                ('pharm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pharms')),
            ],
        ),
    ]
